Amend org name and update to latest version
govuk-one-login/di-fec-ga4-demo pull request #38
Opened 2024-02-08 16:10 UTC by Joanneyoung01

### Description

### Tickets

(DFC-369)[https://govukverify.atlassian.net/browse/DFC-369]

- correct org name in package.json language toggle
- Update all imports of the language toggle

2024-02-08 16:30 UTC, SophiaDWokoma approved these changes

2024-02-09 11:34 UTC, di-fabs requested changes

2024-02-09 11:34 UTC, di-fabs commented on src/views/common/base.njk
> +  <script src="/language-toggle/analytics.js"></script>
don't think this line is needed, no?

2024-02-09 12:07 UTC, di-fabs approved these changes

2024-02-09 12:13 UTC, merged