[DFC-381]: Add accessibility and design amend requests
govuk-one-login/di-fec-ga4-demo pull request #40
Opened 2024-02-23 14:36 UTC by Joanneyoung01

## Description
(DFC-381)[https://govukverify.atlassian.net/browse/DFC-381]

All requirements are detailed on the ticket - these were the points to change as a result of the call with Derren Wilson (Accessibility) and Matt Ashton (UCD).

## Accessibility
- Links to have aria-hidden attribute “change to x” must be in passed into the component in alternate language, so assistive technology reads out “Change to x”
- Aria-roles to be added to the navigation, list and links
- Add hreflang="x" rel="alternate" to links
- Aria-label to be a translated param so that “Choose a language” is localised

## Analytics
- Add link - click:lang-select:{{ lang.code }} to the links

## Design
- Add border bottom to the smaller devices (tablet + mobile)
- Language toggle to be positioned above the back button
- Apply text positioning on a smaller devices - float left

### Steps to Reproduce

If running locally, you need to amend where the component is looking up (from npm registry to the local component)
1. Amend the component import in base.njk to
`{% from "language-toggle/macro.njk" import oneloginLanguageSelect %}`
2. Amend the build-sass command to the below
`"build-sass": "rm -rf public/style.css && sass --no-source-map src/components/language-toggle/stylesheet/styles.css  public/stylesheets/application.css --style compressed"`
2. Run `npm run start`

This will now pick up and build the localised component with all the changes

### Test coverage
![Screenshot 2024-02-23 at 14 25 40](https://github.com/govuk-one-login/di-fec-ga4-demo/assets/38694448/3eaabc78-ab12-49f6-918d-9a82e15b3b92)

### Screenshots
<img width="837" alt="Screenshot 2024-02-22 at 17 43 56" src="https://github.com/govuk-one-login/di-fec-ga4-demo/assets/38694448/e512cf84-c90f-4d73-bf7e-f22c44ca0bfa">
<img width="811" alt="Screenshot 2024-02-22 at 17 43 41" src="https://github.com/govuk-one-login/di-fec-ga4-demo/assets/38694448/d6cb771a-df40-4bef-b62a-b7170674cd36">
<img width="503" alt="Screenshot 2024-02-22 at 17 39 23" src="https://github.com/govuk-one-login/di-fec-ga4-demo/assets/38694448/b520bb06-ab67-42a6-9d42-15a6a0c4009e">

2024-02-26 09:40 UTC, di-fabs requested changes

2024-02-26 09:40 UTC, di-fabs commented on src/views/common/base.njk
> +            visuallyHidden: 'Newid yr iaith ir Gymraeg'
Have you added this new property into the readme?

2024-02-27 09:47 UTC, di-fabs approved these changes

2024-02-27 12:48 UTC, SophiaWokoma approved these changes

2024-02-27 16:39 UTC, SophiaDWokoma approved these changes

2024-02-27 17:26 UTC, merged