DFC-551: Rename one-login-language-toggle to frontend-language-toggle
govuk-one-login/di-fec-ga4-demo pull request #50
Opened 2024-04-22 16:36 UTC by di-aholme

### Description

### Tickets

(DFC-**)[https://govukverify.atlassian.net/browse/DFC-**]

### Steps to Reproduce

### Co-Authored By

### Additional Information

2024-04-23 09:00 UTC, Joanneyoung01 commented on src/components/frontend-language-toggle/README.md
> +   npm install language-toggle
i think we need to keep 

when i run 
`npm install language-toggle` it says not found so i think we need to keep the org name

2024-04-25 11:47 UTC, Joanneyoung01 commented on src/components/frontend-language-toggle/tsconfig.json
> +    // "rootDir": "./src" /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */,
Do we need to keep the comments in?

2024-04-26 14:43 UTC, di-aholme commented on src/components/frontend-language-toggle/tsconfig.json
> +    // "rootDir": "./src" /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */,
Updated and removed the unused config

2024-04-29 14:15 UTC, Joanneyoung01 commented on src/config/nunjucks.js
> +const addLanguageParam = require("@govuk-one-login/frontend-language-toggle/cjs/index.cjs");
Did you mention that this is tested using the commonJS method I can see you’ve imported the below line using a const/require const addLanguageParam = require("@govuk-one-login/frontend-language-toggle/cjs/index.cjs"); in the src/config/nunjucks.js file, should this line be replaced in the screenshot attached? 
[@Andy Holme](https://gds.slack.com/team/U060YSALWP6)
 (edited)

2024-04-29 14:17 UTC, Joanneyoung01 commented on src/config/nunjucks.js
> +const addLanguageParam = require("@govuk-one-login/frontend-language-toggle/cjs/index.cjs");
const addLanguageParam = require("@govuk-one-login/one-login-language-toggle");

2024-04-30 11:05 UTC, SophiaDWokoma requested changes

2024-04-30 11:05 UTC, SophiaDWokoma commented on src/components/frontend-language-toggle/README.md
> +   const addLanguageParam = require("@govuk-one-login/frontend-language-toggle/language-param-setter");
We should also probably add the import version too.
`import addLanguageParam from "@govuk-one-login/frontend-language-toggle";`

2024-04-30 11:25 UTC, Joanneyoung01 approved these changes

2024-04-30 14:26 UTC, SophiaDWokoma approved these changes

2024-04-30 15:31 UTC, merged